### ISSUE TITLE
Can't run `terraform destroy` when using the module.

### ISSUE THREAD

**Issue by JSNortal** [bschaatsbergen/terraform-gce-atlantis#101]
It seems that running `terraform destory` is prevented by the compute instance not deleting it persistent storage causing the error.

```
│ Error: Error when reading or editing Project Service <PROJECT-ID>/compute.googleapis.com: Error disabling service 
"compute.googleapis.com" for project "<PROJECT-ID>": Error waiting for api to disable: Error code 9, message: [Error in service 
'compute.googleapis.com': Could not turn off service, as it still has resources in use.
```

Not sure if this is intentional but I think if the `delete_rule` is changed to `ON_PERMANENT_INSTANCE_DELETION` it would allow you to run `terraform destroy` but not delete the store if you shut down the instance.

**Comment by bschaatsbergen** [comment]
Hi @JSNortal, this is intended.

Using the module we prevent to destroy the persistent storage disk, to protect a user from accidentally running into data loss. I would recommend you to destroy the data disks yourself from the Compute Engine UI.

**Comment by JSNortal** [comment]
Yea that makes sense. Then I think this issue can be closed.
