### ISSUE TITLE
Does Atlantis have to run as a privileged container?

### ISSUE THREAD

**Issue by cblkwell** [bschaatsbergen/terraform-gce-atlantis#102]
Right now, the Atlantis container runs as privileged, but it is unclear why we need to have that set. If we can get it to run as non-privileged, that would be optimal -- otherwise, we should document exactly why it needs to run as privileged so that users understand that need more thoroughly.

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @cblkwell, I'm going to test a non-privileged release as soon as possible.
