### ISSUE TITLE
Update examples to support optional dns/ssl support for cases where domains are managed at another registrar

### ISSUE THREAD

**Issue by eddyv** [bschaatsbergen/terraform-gce-atlantis#105]
https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/main/examples/complete/main.tf#L96-L107 mentions a small section about defining a dns record set (adding an A record) with a managed zone entry.

It would be helpful to mention somewhere that the current implementation is very GCP native or make this part optional.

More context: https://atlantis-community.slack.com/archives/C5MGGAV0C/p1677427493186339

Thanks!

**Comment by bschaatsbergen** [comment]
Considering that not everyone manages their DNS from within GCP, I still would like to support this case.

**Comment by bschaatsbergen** [comment]
Are you currently blocked using this module @eddyv or did you manage to get around it in the meantime?

**Comment by eddyv** [comment]
Been mostly playing around with this in my free time so haven’t made much progress on any workarounds.

**Comment by bschaatsbergen** [comment]
I've been misunderstanding your use case, but to properly understand what you're trying to achieve:

You want to deploy Atlantis on GCP, but you manage your DNS outside of GCP, correct?


> Been mostly playing around with this in my free time so haven’t made much progress on any workarounds.

**Comment by eddyv** [comment]
Yup!

**Comment by bschaatsbergen** [comment]
Hi @eddyv this should just work out of the box if you add an A record for the SSL certificate to wherever you manage your domain name. I've just tried out deploying the module using a domain hosted in AWS (Route 53) and after adding the A record of the GCP load balancer, the Google Managed SSL Certificate was provisioned successfully. 

I'm closing this issue, if there's any problem you're facing feel free to reopen this issue.
