### ISSUE TITLE
Web UI Job View of Plans Not Working Behind IAP 

### ISSUE THREAD

**Issue by scott-standard** [bschaatsbergen/terraform-gce-atlantis#115]
I'm seeing something strange where the "live plan" view via the console UI has strange behavior where sometimes the full plan doesn't display (especially for larger plans). I used your terraform module for GCE setup. If I bypass IAP, everything is showing correctly. 

I know it was mentioned [here](https://github.com/runatlantis/atlantis/issues/2026#issuecomment-1425844099) that this is due to IAP stripping off the bearer authorization header. 

Any ideas for a workaround? Could I put nginx in front of the atlantis docker container to deal with the authorization header issue somehow?

**Comment by bschaatsbergen** [comment]
Hi @scott-standard, thanks for raising this issue. I'm currently not aware of any workaround to bypass this issue, there probably are ways to solve it but it might add some 'magic/complexity' to your deployment.

**Comment by bschaatsbergen** [comment]
Hi @scott-standard I would assume you still face this issue correct, or did you manage to by-pass it? It seems to be an implication between Atlantis itself and IAP combined with the Global Load Balancer. Is it ok if I close the issue on this repo?
