### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by satomi1911** [bschaatsbergen/terraform-gce-atlantis#121]
Hello,

I noticed there's a typo in [README.md](https://github.com/bschaatsbergen/terraform-gce-atlantis/tree/main#enabling-iap). The property should be named oauth2_client_secret instead of auth2_client_secret.

Incorrect:
```
iap = {
  oauth2_client_id    = data.google_secret_manager_secret_version.atlantis_client_id.secret_data
  auth2_client_secret = data.google_secret_manager_secret_version.atlantis_client_secret.secret_data
}
```

Correct:
```
iap = {
  oauth2_client_id    = data.google_secret_manager_secret_version.atlantis_client_id.secret_data
  oauth2_client_secret = data.google_secret_manager_secret_version.atlantis_client_secret.secret_data
}
```

Reference: https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/ff6ec118ce0d9af5d0a64457ffe240c7227ef6fa/main.tf#L322

Thank you for your hard work on this project. I appreciate it!

**Comment by bschaatsbergen** [comment]
Hi @satomi1911 thanks a lot for raising this issue! 👏🏼 

I've prepared a pull request to address this.
