### ISSUE TITLE
Expose all inputs on container-vm google module

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#23]
https://registry.terraform.io/modules/terraform-google-modules/container-vm/google/latest?tab=inputs

https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/fbc3134ea4f365659ff4d87a589ccb63fdf81429/atlantis.tf#L8-L10

Also you might as well move all the atlantis.tf stuff to main.tf to keep it together since its not that different to warrant a different file name, no?

**Comment by bschaatsbergen** [comment]
`atlantis.tf` is moved to `main.tf`

The `terraform-google-modules/container-vm/google` is just generating metadata which is passed to the konlet-startup service, besides the current inputs nothing needs to be passed down to that interface.
