### ISSUE TITLE
feat: More outputs

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#39]
Consider outputting the entire `module.atlantis`

https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/8bf8716cd15ed55ffcf7063684a80dd7953eb354/main.tf#L110-L112

```hcl
output "atlantis" {
  value       = module.atlantis
  description = "All of the outputs of the upstream terraform-google-modules/container-vm/google module"
}
```

**Comment by bschaatsbergen** [comment]
We actually don't have this available in the state, it's a rendered metadata script. I'll put in some effort to come up with additional relevant outputs though :+1:
