### ISSUE TITLE
Consider using null label for naming convention

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#57]
See the null label

https://github.com/cloudposse/terraform-null-label

This is the mixin thats used across all cloudposse modules

https://github.com/cloudposse/terraform-null-label/blob/master/exports/context.tf

This allows using standard inputs such as namespace, tenant, environment, name, attributes, tags, etc

Example of usage

https://github.com/cloudposse/terraform-aws-ecr

https://github.com/cloudposse/terraform-aws-ecr/blob/master/context.tf

https://github.com/cloudposse/terraform-aws-ecr/blob/0472d649275df45dfd47514275e69792d1567d08/main.tf#L8

So this results in all name arguments set to this value

```hcl
  name = module.this.id
```

**Comment by bschaatsbergen** [comment]
As of now I don't see the added value of the null label module, we can consider it in the nearby future.
