### ISSUE TITLE
tests: Consider terratest

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#58]
For testing this module.

Example https://github.com/cloudposse/terraform-aws-ecr/tree/master/test/src

**Comment by bschaatsbergen** [comment]
As of now I don't see the added value of adding terratest to this module. We can reconsider this later.

**Comment by nitrocode** [comment]
That's surprising. Unit testing terraform modules is one of the best ways to avoid introducing breaking changes.
