### ISSUE TITLE
Consider using `default` for your resource names instead of reusing `atlantis`

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#61]
Module usage

```hcl
module "atlantis" {
  source  = "bschaatsbergen/atlantis/gce"
  version = "0.1.5"
  # insert the 7 required variables 
}
```

Then a resource like this

https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/88f71057b47fd89d31da5a8c57c4bd8f08a2615d/main.tf#L14

Would have a fully qualified address of `module.atlantis.google_compute_instance_template.atlantis` which is redundant.

Consider using `default` for your resource names instead of reusing `atlantis` which would result in a fully qualified address of `module.atlantis.google_compute_instance_template.default`

**Comment by bschaatsbergen** [comment]
This would be a very large breaking change, but as we're still under pre-release I think that we can pull this off.
