### ISSUE TITLE
what is mig

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#62]
https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/88f71057b47fd89d31da5a8c57c4bd8f08a2615d/main.tf#L158-L159

**Comment by bschaatsbergen** [comment]
abbreviated: managed instance group, we require a less aggressive health check on the managed instance group then we do on the load balancer, to prevent instances from being recreated by the [auto healing policy](https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/main/main.tf#L192-L195).
