### ISSUE TITLE
tests: Scan module with a sast or dast as a pr check

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#63]
See tflint, tfsec, checkov

These can be run in pre commit hooks and can be run as a pr check

**Comment by bschaatsbergen** [comment]
there's a pending issue with checkov preventing us from using it unfortunately: https://github.com/bridgecrewio/checkov/issues/4205

**Comment by nitrocode** [comment]
You can enable githubs codeql as well

**Comment by bschaatsbergen** [comment]
I'll be adding checkov soon to pre-commit 👍🏼
