### ISSUE TITLE
startup script improvements

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#66]
https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/main/startup-script.sh

Use set -e

Use /usr/bin/env bash instead of /binbash

Use shellcheck to see if it catches anything

Run shellcheck in github action whenever shell script is modified

**Comment by bschaatsbergen** [comment]
Adding shellcheck to pre-commit in #68

**Comment by bschaatsbergen** [comment]
Meanwhile, we actually plan on moving away from the startup script by porting it to cloudinit. This would make it possible so that a user can provide a startup script and no existing functionality is broken.

Meaning, the GCE persistent disk mounting will still be down, through cloudinit.

See #69

**Comment by bschaatsbergen** [comment]
Closing this in favor of #69, which will also revert the shellcheck changes made at some point.
