### ISSUE TITLE
Option to put GCP IAP in front of atlantis

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#86]
Related tickets

- https://github.com/runatlantis/atlantis/issues/827
- https://github.com/runatlantis/atlantis/issues/2883#issuecomment-1385037466
- https://github.com/runatlantis/atlantis/issues/2904#issuecomment-1375685628

**Comment by bschaatsbergen** [comment]
IAP has been added in #78
